server:
  port: 8080
spring:
  cloud:
    function:
      definition: producer
    stream:
      bindings:
        producer-out-0:
          destination: user
    gcp:
      pubsub:
        project-id: abekoh-sand
      #        emulator-host: localhost:8085
      credentials:
        location: file:/Users/abekoh/.gcp/reactive-messaging-sample.json